### PR TITLE
Add Gujarati language translation!

### PR DESCRIPTION
**Pull request by pixan198**
#### Is your pull request related to a problem? Please describe
It adds the Gujarati Language support as per #57 

#### Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/master/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added the label **enhancement** to my pull request.

### CODE REVIEW

**Comment by pixan198** [comment]
@elinguiuriel @aboullaite Can you please review this PR?

**Comment by aboullaite** [comment]
Thank you @pixan198 for taking tame adding support for Gujarati. Unfortunately neither me nor @elinguiuriel speak Gujarati! We're waiting for community help on that one. would you recommend someone that can help ?

**Comment by elinguiuriel** [comment]
> Thank you @pixan198 for taking tame adding support for Gujarati. Unfortunately neither me nor @elinguiuriel speak Gujarati! We're waiting for community help on that one. would you recommend someone that can help ?

@pixan198 seems to be a native speaker, morphologically it seams OK,  It's OK for me to merge his PR, another native speaker may update it later

**Comment by pixan198** [comment]
@aboullaite I couldn't find anyone right now, but it would be great if someone from community can help us for this.

@elinguiuriel Yes, I'm a native speaker of gujarati language.

**Comment by elinguiuriel** [comment]
@pixan198 I merge your PR as you can see, share it in your community 
nice work 🥇 

image

image

**Comment by pixan198** [comment]
@elinguiuriel Yes, it's working fine. 🤩

**Pull request merged**
