### PR TITLE
Add yaml contributors

### PR DESCRIPTION
**Pull request by kabahima**

### CODE REVIEW

**Comment by aboullaite** [comment]
@kabahima Please signe fb CLA at https://code.facebook.com/cla.

**Comment by aboullaite** [comment]
@kabahima This PR has conflicts! can you please fix them ?

**Comment by Awinja-j** [comment]
@kabahima great PR!

Please solve the conflicts to that we can have it merged soon.

Thank you for your contribution.

**Review by elinguiuriel — COMMENTED** [review]
Corrected!

**Pull request merged**
