### PR TITLE
Adding contributors section

### PR DESCRIPTION
**Pull request by vinitshahdeo**
#### Is your pull request related to a problem? Please describe
The Contributors section in `README.md` is missing.

#### Describe the solution you'd like
- Added a list of contributors with a [link](https://github.com/fbdevelopercircles/open-source-edu-bot/graphs/contributors) to the contributions graph
- Added a [PRs Welcome](http://makeapullrequest.com/) badge which links to [CONTRIBUTING.md](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/master/CONTRIBUTING.md)

[PRs Welcome](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/master/CONTRIBUTING.md)

#### Additional context

I suggest you to add [Hall of Fame](https://github.com/sourcerer-io/hall-of-fame) in `README.md` under contributors section.

#### Checklist
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **[CONTRIBUTING](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/master/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added the label **enhancement** to my pull request.

### CODE REVIEW

**Comment by aboullaite** [comment]
Such a great feature @vinitshahdeo. Thank you! However, I was thinking about it and it inspired me to push it a little further by automating this process 💯  Something like [all-contributors-bot](https://github.com/all-contributors/all-contributors-bot) could really help us here.

WDYT ?! Is this something you can work on ?

**Comment by vinitshahdeo** [comment]
@aboullaite Hey, thanks for the quick response. Yes, I can work upon adding the [all-contributors-bot](https://github.com/all-contributors/all-contributors-bot). What do you think about [Hall Of Fame](https://github.com/sourcerer-io/hall-of-fame)? Which one shall we go for?

PS: To add these bots, I need to be a member of the [org](https://github.com/fbdevelopercircles/), can you please invite me?

**Comment by aboullaite** [comment]
Both are valid solution IMO! I have a slightly preference for all-contributors-bot. @caabernathy @elinguiuriel @Awinja-j WDYT ?

**Comment by caabernathy** [comment]
I like both as well. The leaderboard like nature of Hall of Fame makes it more interesting to me. Unfortunately it doesn't give love to everyone so all contributors may be best in the short term.

**Comment by vinitshahdeo** [comment]
@aboullaite @caabernathy @tvalentius Finally, are we going with [Hall Of Fame](https://github.com/sourcerer-io/hall-of-fame)?

> See Hall Of Fame in action [here](https://github.com/vinitshahdeo/Water-Monitoring-System/#mentors).

**Comment by elinguiuriel** [comment]
@vinitshahdeo ok for me !

**Comment by vinitshahdeo** [comment]
@elinguiuriel Org access is required to generate **Hall of Fame**. Can you please invite me to the org?

**Comment by aboullaite** [comment]
@vinitshahdeo adding the Bot to the org is a WIP! We already submitted a request to devc team :) keep you posted

**Comment by aboullaite** [comment]
@vinitshahdeo Adding the bots won't be possible in the near future. What we could do instead is something I described in #37! Wdyt @caabernathy @elinguiuriel @Awinja-j

**Comment by caabernathy** [comment]
I would agree with you on your recommendation @aboullaite.

**Comment by aboullaite** [comment]
I believe we can close this PR as we have now a clear vision described in #37

**Pull request closed without merging**
