### PR TITLE
WIP: Chinese localization

### PR DESCRIPTION
**Pull request by prilcool**
This is the initial  work in progress commit for the Chinese localization (Simplified chinese) .
Completed is localization up-till line 78 .
Whats left is to continue translation from line  78 onwards . 

This can be merged so others can pull it and continue translating 👍  .

Team members can continue translation by referencing the  English to Hindi translation .po  located in the hi folder.

### CODE REVIEW

**Comment by aboullaite** [comment]
We cannot merge this PR until its completed or we risk to have a bad user experience! If other want to complete this work, please feel free 🙏

**Comment by prilcool** [comment]
ok  sure  I'll  resubmit when i'm done  :) 

But just  note  :
This is just a  .po localization   file and it's not active and not implemented  , no one will have  any experience unless and until they go and activate it .   :)

**Comment by aboullaite** [comment]
```
Use google translate to convert from english to simplified chinese and than recheck from simplified chinese to english
```
@prilcool this is more of a hack than a useful translation. We want users of the bot to have a decent experience, that I strongly believe cannot be achieved using google translate. Either keep it in english or translate to a language you are confident to use. Please refer to our discussion with @elinguiuriel in #57.
Closing this for now, feel free to open if you wanna add anything

**Comment by prilcool** [comment]
I believe you probably need more experience in this area . 
Google translation  accuracy is very good provided you know how to use it .
I guess that is the difference between knowing how to use a tool the correct way and not knowing .

**Pull request closed without merging**
