### PR TITLE
Enhancement of README.md with grammar corrections

### PR DESCRIPTION
**Pull request by sailikhithk**
The punctuations, articles that are missing are placed appropriately and cross-checked with apps like Grammarly. Everything is perfect with this updated READ ME.md

#### Is your pull request related to a problem? Please describe
A clear and concise description of what the problem is. Ex. I'm always frustrated when ...

#### Test plan
A good test plan should give instructions that someone else can easily follow.
Also add a link to your own Messenger experience for your reviewer to test the changes.

#### Checklist
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/master/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have added the label **enhancement** to my pull request.

### CODE REVIEW

**Comment by sailikhithk** [comment]
My CLI agreement was successful with my Github. Please see this as a reference.
image

**Comment by sailikhithk** [comment]
Please merge this pull request into the README file as 13 grammar mistakes were corrected, this would be helpful for the fellow contributors to go through in future,

**Comment by elinguiuriel** [comment]
@sailikhithk welcome and thanks to you for your contribution! feel free to pick another in the issues tab!

**Comment by sailikhithk** [comment]
Sure @elinguiuriel , I shall be working on it. Thanks for merging my pull request. Happy to contribute more.

**Pull request merged**
