### PR TITLE
Support for spanish language

### PR DESCRIPTION
**Pull request by Cegard**
#### Is your pull request related to a problem? Please describe
A clear and concise description of what the problem is. Ex. I'm always frustrated when ...

#### Test plan
A good test plan should give instructions that someone else can easily follow.
Also add a link to your own Messenger experience for your reviewer to test the changes.

#### Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/master/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added the label **enhancement** to my pull request.

### CODE REVIEW

**Comment by aboullaite** [comment]
Thanks for your contribution @Cegard. Can you please fix conflicts!

**Comment by Cegard** [comment]
Conflicts were fixed again.

**Comment by Cegard** [comment]
Conflicts were fixed again.

**Comment by elinguiuriel** [comment]
@Cegard thank you so much, I love when someone adds a new language to the bot

**Comment by elinguiuriel** [comment]
@Cegard make sure your facebook language is spanish and test the chabot here https://m.me/OpenSourceChatbot

image

Pay attention to untranslated phrases that you can correct in a new PR :-) !

**Comment by Cegard** [comment]
Hi @elinguiuriel I'm glad to contribute to this project. I took a look at the untranslated text and I decided that the way to go with this was adding the `msgid` in the `messages.po`, but I'm not sure if this is the proper fix or just a workaround, What do you think?

**Pull request merged**
